project:
  type: book
  output-dir: docs

book:
  title: Semiautomated classification of Fin Whales in the California Current
  subtitle: The subtitle
  date: January 2023
  downloads: [pdf, docx]
  author:
  - name: Cory Hom-Weaver
    email: cory.hom-weaver@noaa.gov
    affiliations:
      - id: swfsc-mmtd
        name: Southwest Fisheries Science Center
        department: Marine Mammal and Turtle Department
        address: 
          - 8901 La Jolla Shores Drive
          - La Jolla, California 92037
  - name: Shannon Rankin
    affiliations:
      - ref: swfsc-mmtd
  - name: Taiki Sakai
    affiliations:
      - ref: swfsc-mmtd
  chapters:
    - index.qmd
    - text/Intro.qmd
    - text/conclusion.qmd
    - text/references.qmd

  site-url: https://nmfs-opensci.github.io/NOAA-tech-memo-template/
  repo-url: https://github.com/chomweaver/test_techmemo
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
